stages:
  - build
  - docker
  - doploy

build:
  stage: build
  image: 'docker.lcgc.work/fe/global-fe:0.5.5'
  only:
    - dev
    - pre
    - /^\d+\.\d+\.\d+$/
  script:
    - cnpm install
    - cnpm run build
  artifacts:
    name: '${CI_BUILD_STAGE}_${CI_BUILD_ID}'
    paths:
      - dist/
    expire_in: 1d

docker-dev:
  stage: docker
  image: 'docker:dind'
  when: on_success
  only:
    - dev
  before_script:
    - export BUILD_PATH=$(pwd)
    - export IMAGE_NAME=docker.lcgc.work/${CI_PROJECT_PATH}:dev-${CI_PIPELINE_ID}
  script:
    - docker build -t ${IMAGE_NAME} ${BUILD_PATH}
    - docker push ${IMAGE_NAME}

docker-pre:
  stage: docker
  image: 'docker:dind'
  when: on_success
  only:
    - pre
  before_script:
    - export BUILD_PATH=$(pwd)
    - export IMAGE_NAME=docker.lcgc.work/${CI_PROJECT_PATH}:pre-${CI_PIPELINE_ID}
  script:
    - docker build -t ${IMAGE_NAME} ${BUILD_PATH}
    - docker push ${IMAGE_NAME}

docker-prod:
  stage: docker
  image: 'docker:dind'
  when: on_success
  only:
    - /^\d+\.\d+\.\d+$/
  before_script:
    - export BUILD_PATH=$(pwd)
    - export IMAGE_NAME=docker.lcgc.work/${CI_PROJECT_PATH}:prod-${CI_COMMIT_REF_NAME}
  script:
    - docker build -t ${IMAGE_NAME} ${BUILD_PATH}
    - docker push ${IMAGE_NAME}

deploy-dev:
  stage: doploy
  image: 'docker.lcgc.work/kubectl'
  when: on_success
  dependencies: []
  only:
    - dev
  environment:
    name: dev
  before_script:
    - export CIK8S_CONFIG_TARGET=stage
    - export CIK8S_CONFIG_TOKEN=${STAGE_KUBE_TOKEN}
    - export CIK8S_CONFIG_REPLICAS=1
    - export CIK8S_CONFIG_IMAGE=docker.lcgc.work/${CI_PROJECT_PATH}:dev-${CI_PIPELINE_ID}
    - export CIK8S_ENV_NGINX_UPSTREAM=fe-global-solar-fe
    - export CIK8S_ENV_NGINX_TARGET=kube-test
    - export CIK8S_PORT_NGINX_PORT=
  script:
    - deploy

deploy-pre:
  stage: doploy
  image: 'docker.lcgc.work/kubectl'
  when: on_success
  dependencies: []
  only:
    - pre
  environment:
    name: pre
  before_script:
    - export CIK8S_CONFIG_TARGET=pre
    - export CIK8S_CONFIG_TOKEN=${RELEASE_KUBE_TOKEN}
    - export CIK8S_CONFIG_REPLICAS=1
    - export CIK8S_CONFIG_IMAGE=docker.lcgc.work/${CI_PROJECT_PATH}:pre-${CI_PIPELINE_ID}
    - export CIK8S_ENV_NGINX_UPSTREAM=fe-global-solar-fe
    - export CIK8S_ENV_NGINX_TARGET=kube
    - export CIK8S_PORT_NGINX_PORT=
  script:
    - deploy

deploy-prod:
  stage: doploy
  image: 'docker.lcgc.work/kubectl'
  when: manual
  dependencies: []
  only:
    - /^\d+\.\d+\.\d+$/
  environment:
    name: prod
  before_script:
    - export CIK8S_CONFIG_TARGET=release
    - export CIK8S_CONFIG_TOKEN=${RELEASE_KUBE_TOKEN}
    - export CIK8S_CONFIG_REPLICAS=2
    - export CIK8S_CONFIG_IMAGE=docker.lcgc.work/${CI_PROJECT_PATH}:prod-${CI_COMMIT_REF_NAME}
    - export CIK8S_ENV_NGINX_UPSTREAM=fe-global-solar-fe
    - export CIK8S_ENV_NGINX_TARGET=kube
    - export CIK8S_PORT_NGINX_PORT=
  script:
    - deploy
